### ISSUE TITLE
items disappearing after identification

### ISSUE THREAD

**Issue by Grog5** [Secrets-of-Sosaria/World#1]
The bug with the things disappearing after identification remains:

The following Item disappared after identification with arms lore  

###################################################
CUO version: 3.23.0.0
OBJECT TYPE: ClassicUO.Game.GameObjects.Item
AllowedToDraw = True
AlphaHue = 0
Amount = 1
Container = 1074355484
Direction = North
Distance = 3642
Flags = None
Graphics = 0x2643
HP = 0/0
Hue = 0x0803
IsCoins = False
IsMulti = False
Layer = Invalid
MultiGraphic = 0x0000
Position = X=149, Y=69, Z=0
Price = 0
PriorityZ = 0
Serial = 0x40078A25
###################################################

![grafik](https://github.com/user-attachments/assets/8528e5f1-3fe7-4a3e-86da-8257d463acc2)
![grafik](https://github.com/user-attachments/assets/94972068-ac2a-4d06-8c59-ebfafb18c98a)

**Comment by creiht** [comment]
I've taken a stab at fixing this issue if you would like to try it out.
