### ISSUE TITLE
[Bug] Scepters and staves should have spell channeling

### ISSUE THREAD

**Issue by cpzjunior** [Secrets-of-Sosaria/World#102]
Like wands, scepters and staves are weapons used primarily by wizards. However, they do not have spell channeling by default. Whenever I use a spell, they are unequipped, which makes it difficult for my wizard to play, since I am forced to equip them again every time.

**Comment by creiht** [comment]
Looking at the code, it is evident that these items were created for wizards (file name is `WizardStaff.cs`), so I would be on board with making a change like this, but also open to hearing other's opinions here.

I also noticed that there are no requirements to be a wizard to use them or their special ability.  So I guess the question also comes up, should some level of magic skill be required to use them, or the damage leveled by their magic skill?

**Comment by mz1193** [comment]
> Looking at the code, it is evident that these items were created for wizards (file name is `WizardStaff.cs`), so I would be on board with making a change like this, but also open to hearing other's opinions here.
> 
> I also noticed that there are no requirements to be a wizard to use them or their special ability. So I guess the question also comes up, should some level of magic skill be required to use them, or the damage leveled by their magic skill?

I'm not sure if adding hard wizard requirements for staves, specifically, is necessary. I can imagine character concepts that would use staves as primary weapons but not necessarily have any magic ability (some sort of martial arts style monk build, for instance.) As for scepters, I can't give a specific example off the top of my head, but I'm also not sure those are seen as strictly"mage-y" weapons.

Regarding the change itself, I think the idea is a good one!

**Comment by Kynick** [comment]
I've always thought it a bit silly that these dont have SC by default.  its the reason Ive been a punching elementalist instead of using them

**Comment by mz1193** [comment]
> Looking at the code, it is evident that these items were created for wizards (file name is `WizardStaff.cs`), so I would be on board with making a change like this, but also open to hearing other's opinions here.
> 
> I also noticed that there are no requirements to be a wizard to use them or their special ability. So I guess the question also comes up, should some level of magic skill be required to use them, or the damage leveled by their magic skill?

I've been working on this a bit today, and interestingly enough, these weapons do actually complain about you "not being a powerful enough mage" if you attempt to equip them on a low-skilled character. However, I don't see references to it in this specific file, so I wonder if it's pulling from somewhere else?

In any case, I figured out how to add spell channeling to these weapon types and will be submitting a PR for that shortly!

**Comment by mz1193** [comment]
PR is submitted, but I would appreciate some local testing from those who play characters like this. It's a very simple change and should just work, but you never know!

**Comment by mz1193** [comment]
More testing done on my end seems to indicate that this fix is working as intended. Considering that it's been merged into main already, would someone mind closing this issue? Thank you!

**Comment by cpzjunior** [comment]
Ok, I'm closing the issue, thanks.
