### ISSUE TITLE
"Simply Drawn" Treasure Maps Are Unusable.

### ISSUE THREAD

**Issue by Veavictis** [Secrets-of-Sosaria/World#112]
They give the error when trying to decode them "This treasure map can only be used by a young player." - They have accounted for about 30% of my t map drops and should either be removed from the loot pool, or made usable, please. Thank you!

**Comment by creiht** [comment]
The attached pull request should fix this issue, but would appreciate some offline testing just to be sure that digging up 0 level treasure chests don't cause any issues.
