### ISSUE TITLE
[suggestion] items with +skill bonuses should not override skill cap

### ISSUE THREAD

**Issue by EstelMatiazi** [Secrets-of-Sosaria/World#131]
Currently, the abundance of gear with bonuses to skills makes powerscrolls pointless. 

From a game balance perspective, I think its important to restrict the bonuses that a player can get from gear to their current cap, so if a player has a maximum of 100 points in a skill, skill bonuses from items should not get the player over 100 points. This will make power scrolls desirable to fine tune builds and increase the amount of choice when spending skill points, as well as giving an use to gold.

**Comment by Kynick** [comment]
I'm for it

**Comment by mz1193** [comment]
This will go a long way in encouraging specialized characters and making power scrolls more appealing. Great idea!
