### ISSUE TITLE
[bug] Mirror images are grey.

### ISSUE THREAD

**Issue by Tierloc** [Secrets-of-Sosaria/World#143]
While in animal form instead of blue copies of the player they're grey and the client/razor treats them as non-friendlies.

**Comment by EstelMatiazi** [comment]
animal forms come with the default notoriety of the form you assume. A clone of a snake will be red, of a cat will be grey. Thats how default UO behaves.

**Comment by Tierloc** [comment]
Withdrawn then, seems counter intuitive that I'm not also grey or red but don't need to fix what isn't broke.
