### ISSUE TITLE
[Bug] Snakes of the chamber of the balance quest do not respawn

### ISSUE THREAD

**Issue by cpzjunior** [Secrets-of-Sosaria/World#144]
I did the balance quest with my main character a few days ago. Then, I went to do it with my secondary character. Once I got the three serpents from dungeon bane, I went to the chamber of the dungeon of serpent sanctum and got the balance piece. However, I can't kill the two black rock serpents because they simply aren't there. Checking with other players, it seems to be a bug from the R&R era, which requires admin intervention to force the respawn, so I believe there may be a missing timer or there may be a problem with the spawner in this room.
![1](https://github.com/user-attachments/assets/f02353aa-4d11-42b5-9b6d-8510fd7caf1a)

**Comment by cpzjunior** [comment]
Just to clarify, this has been happening for a few days now, and other players have reported that they've been checking for weeks, so it might be a case of them only respawning when the server restarts.

**Comment by EstelMatiazi** [comment]
a fix has been merge into the repo, please close this issue.

**Comment by cpzjunior** [comment]
Ok, I'm closing the issue, thanks.
