### ISSUE TITLE
Grizzled Mare statue and Skeletal Steed is bonded but cannot be resurrected

### ISSUE THREAD

**Issue by NoobixCube** [Secrets-of-Sosaria/World#24]
Using grizzled mare statue spawns a bonded skeletal steed which can be ridden.
After death, the pet remains bonded but cannot be resurrected or healed.
Attempts to resurrect say the target is not dead and attempts to heal say that you cannot heal a creature that is already dead.

**Comment by AxelDominatoR** [comment]
That happens to any pet, not just the skeletal steed: veterinary seems to be the only way of resurrecting them yourself. Any druid NPC will also resurrect them.
Removing the ability to resurrect pets via spells may have been done on purpose.

**Comment by sosarian-scribe** [comment]
This seems to be a feature not a bug? You are not supposed to be able to res pets with conventional healing, right?

**Comment by NoobixCube** [comment]
To be fair, I did NOT try and visit a druid but the Vet NPC in Brit did not even try to bring it back.
Unfortunately, I just released the poor thing since I couldn't seem to figure out a way to bring it back.
Can't test now.

**Comment by creiht** [comment]
Yeah the Grizzled Mare is considered a Skeletal Mount and thus and Animated Dead type, so it can't be healed or resurrected by bandages.  There are other means that the mount could have been resurrected though...
