### ISSUE TITLE
[bug] skill titles fail to take character gender into consideration

### ISSUE THREAD

**Issue by EstelMatiazi** [Secrets-of-Sosaria/World#26]
Currently, regardless of your gender, if you set your title to swordsmanship or arms lore you will endup with 'swordsman' or 'man-at-arms' as your title. 

The file skills.cs has a few commented lines that are supposed to deal with this in the CharacterTitle function, but they are commented. Uncommenting them seemed to do nothing.

**Comment by mz1193** [comment]
Great issue. Always bugged me how I could never have "Swordswoman" as a title. I seem to recall other custom UO servers in the past had methods to do this. I want to say Excelsior was one of them?
