### ISSUE TITLE
[bug] paralyze duration is often longer than the skill cooldown

### ISSUE THREAD

**Issue by EstelMatiazi** [Secrets-of-Sosaria/World#33]
In the terathan keep, the terathan warriors have a 15 seconds long cooldown, calculated by ((double)(this.Fame/200))  in basecreature.cs at capping at 15 secs.

This leads to situations where high fame monsters that you don't one shot will flee and chain-paralyze you, and with nothing else in range, you can be stuck there for full minutes waiting for the monster to regen enough to come back and fight you.

Proposed solution: add a global setting for maximum paralyze duration and cap it at 5 seconds.

**Comment by Tultra** [comment]
I've also faced this problem. I need to remember the name of the creature (it was Deep Elemental or something, a large green glob of mold). But in my case the cooldown was certainly smaller than 15 seconds. I took me a few minutes before I was able to get away.

I think we should either reduce the duration cap (as proposed), increase the overall cooldown, or add some sort of diminishing returns on paralyze: starting with 10 secs, than 7 secs, than 3 secs, than 1 sec (or immune) for consecutive casts in a certain timespan.
