### ISSUE TITLE
[bug] Herbalist sells Water Plant that results in Reeds

### ISSUE THREAD

**Issue by dmensinger** [Secrets-of-Sosaria/World#35]
As description says, the Alchemist, specifically in Moon, sells what is labeled as a 'Water Plant' but delivers 'Reeds' upon purchase.

**Comment by creiht** [comment]
It looks like the "Water Plant" is a collection of plants, and when you buy it can be 1 of 6 different plants, which includes reeds.

**Comment by dmensinger** [comment]
Ahh ok i purchased two and they were both the same so i assumed. This can be marked resolved

**Comment by dmensinger** [comment]
Closing this issue
