### ISSUE TITLE
[bug] Item: The Mighty Anvil [of Immus Bluehand] has syntax error

### ISSUE THREAD

**Issue by dmensinger** [Secrets-of-Sosaria/World#36]
Item found as loot with blue name: 'The Mighty Anvil of Immus Bluehand' displays BASEFONT COLOR markup when single clicking it. See attached

![Screenshot 2024-10-17 213732](https://github.com/user-attachments/assets/1123b5e2-72fa-43c7-988b-3d021ec9053e)

**Comment by creiht** [comment]
I think I have figured out a fix for this.  Would the preference to be to not show anything when clicked on (like most other rares?) or show "anvil" like other anvils?

**Comment by dmensinger** [comment]
To me this comes across as another magical item but ill let you guys decide. Thanks for the fix
