### ISSUE TITLE
[bug] skinning liches is giving xeno bones

### ISSUE THREAD

**Issue by EstelMatiazi** [Secrets-of-Sosaria/World#41]
![image](https://github.com/user-attachments/assets/ccc2fa7c-0908-4639-a773-58a6145581a9)

**Comment by creiht** [comment]
In the code, all of the liches are specifically overridden to have xeno type skeletons, and appears to be intentional.

**Comment by EstelMatiazi** [comment]
But does it make sense? The game has lich bones as a crafting material, shouldn't it drop from...liches?

**Comment by creiht** [comment]
Yeah it is odd for sure, and requires more research.

**Comment by creiht** [comment]
After doing some more digging, I agree with Estel that these should be changed to Lich bones.  If anyone wants to take a stab, find the lich source files that have this line:

`		public override SkeletalType SkeletalType{ get{ return SkeletalType.Xeno; } }`

and replace with:

`		public override SkeletalType SkeletalType{ get{ return SkeletalType.Lich; } }`
