### ISSUE TITLE
[Bug]Elementalist Mount changed after update

### ISSUE THREAD

**Issue by Kynick** [Secrets-of-Sosaria/World#50]
![image_2024-10-20_213130473](https://github.com/user-attachments/assets/d0af1cd2-0d5b-4bb9-82cf-74ce9d14ffc1)

Second time loading up the game after the Valor update.  World rebuilt itself again, though I didn't change anything after the first.  Also, my Elementalist mount should not be horse-shaped...

Releasing and resummoning brought back the normal graphic *shrug*

**Comment by creiht** [comment]
Is the only difference the graphic of the mount?  Does it still have the original color, sounds,  etc?

**Comment by Kynick** [comment]
As for sounds, I couldn’t say, I don’t play with sound.  The phoenix-horse kept its color, but the bear-horse didnt(I suspect because the bear was regular color and the phoenix was an orange-dyed something

**Comment by creiht** [comment]
I was able to duplicate the issue by summoning the mount and running `[buildworld` as admin.

This change seems to fix it, but would appreciate some offline testing.
