### ISSUE TITLE
[suggestion] Magic Skeleton Key is too common and makes lockpicking hard to justify

### ISSUE THREAD

**Issue by EstelMatiazi** [Secrets-of-Sosaria/World#68]
Currently, the magic skeleton key is a rare item that unlocks anything (except for alien containers) with no charge limit:
![image](https://github.com/user-attachments/assets/f9088365-486b-4b5c-a4d9-e8e25e2b00c9)

Upon discussion, it was proposed that it was turned into an artifact to bring it more inline with other items that nullify game systems (like the everlasting loaf).

**Comment by uohaloran** [comment]
I think this is a pretty good compromise!

**Comment by creiht** [comment]
I would be on board with that idea.  It would also appear that in the code, there used to be a 1 in 10 chance that the magic skeleton key would be consumed.  I think that is also another possible answer.

**Comment by mz1193** [comment]
> I would be on board with that idea. It would also appear that in the code, there used to be a 1 in 10 chance that the magic skeleton key would be consumed. I think that is also another possible answer.

Interesting find! I'd support bringing that back to solve this as long as @EstelMatiazi thinks it's a fair compromise.

**Comment by EstelMatiazi** [comment]
I think we should do one or the other, not both.
