### ISSUE TITLE
[BUG] Executioner's Axe should be "great axe"

### ISSUE THREAD

**Issue by creiht** [Secrets-of-Sosaria/World#75]
It seems that the Executioner's Axe was renamed to a "great axe" in crafting, but the BODs list it as an Executioner's Axe which can cause confusion.

![image](https://github.com/user-attachments/assets/488772d4-f078-4602-bb63-5abb5db6b0f7)

**Comment by EstelMatiazi** [comment]
do we keep it as executioner axe or great axe?

**Comment by creiht** [comment]
That's actually a good question, I don't have a strong opinion there, other than making it consistent.

**Comment by mz1193** [comment]
Always looked more like an executioner's axe in its form to me.
